name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  everything:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU
      run: sudo apt install qemu-system
    - name: Install nightly
      run: rustup toolchain install nightly; rustup override set nightly
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: Install cargo-xbuild
      run: cargo install cargo-xbuild
    - name: Install bootimage
      run: cargo install bootimage
    - name: Build
      run: cargo xbuild
    - name: Test
      run: cargo xtest
